### ISSUE TITLE
Allow Magic Commands causes SyntaxError

### ISSUE THREAD

**Issue by sparklost** [asiloisad/pulsar-linter-ruff#3]
When `Allow Magic Commands` is activated, this and similar lines:
```py
_ = "test"
for i, _ in enumerate([1, 2, 3]):
```
causes `SyntaxError: Invalid assignment target` right where `_` char is.
Definitely coming from [this](https://github.com/bacadra/pulsar-linter-ruff/blob/master/lib/main.js#L201) or next line.

**Comment by asiloisad** [comment]
Thank you for your report. It's my fault, I forgot cases like yours. I have fixed it and released a newer version. Kind regards
